name: test

on: [pull_request, workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v4
        with:
          component: true